
### **Chat Service**
openapi: 3.0.1
info:
  title: Chat Service
  version: 1.0.0
paths:
  /conversations:
    post:
      tags:
        - chat        
      summary: Create a conversation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items:
                    type: string
                tenantId:
                  type: string
      responses:
        '201':
          description: Conversation created

  /messages:
    get:
      tags:
        - chat    
      summary: Get messages for a conversation
      parameters:
        - name: conversationId
          in: query
          required: true
          schema:
            type: string
        - name: tenantId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of messages
    post:
      summary: Send a message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId:
                  type: string
                senderId:
                  type: string
                text:
                  type: string
                tenantId:
                  type: string
      responses:
        '201':
          description: Message sent