apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-api
  name: user-api
  namespace: multitanentapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - image: 
        env:
          - name: ENV_NAME
            value: "prod"
          - name: LOG_LABEL
            value: "user-api"
          - name: LOG_LEVEL
            value: "info"
          - name: PUBSUB_TOPIC
            value: "projects/ul-ce-p-902564-prj/topics/multitanentapp-prod"          
        imagePullPolicy: Always
        name: user-api
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: multitanentapp-service
      terminationGracePeriodSeconds: 30
      
      